# Generated by Django 3.1.7 on 2021-02-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_name', models.CharField(max_length=200)),
                ('transaction_amount', models.FloatField()),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
